name: Build Windows EXE
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller ccxt pandas numpy rich
      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --console --name crypto_4h_signal_app crypto_4h_signal_app.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crypto-exe
          path: dist/crypto_4h_signal_app.exe
